In [2]:
# import numpy as np
# import pandas as pd
# from copy import deepcopy
# data = pd.read_csv('kmeans.csv', index_col=False)
# data

X1   X2
0  5.9  3.2
1  4.6  2.9
2  6.2  2.8
3  4.7  3.2
4  5.5  4.2
5  5.0  3.0
6  4.9  3.1
7  6.7  3.1
8  5.1  3.8
9  6.0  3.0

In [2]:
# x1 = data['X1'].values
# x2 = data['X2'].values
# X = np.array(list(zip(x1,x2)))
# X

array([[5.9, 3.2],
       [4.6, 2.9],
       [6.2, 2.8],
       [4.7, 3.2],
       [5.5, 4.2],
       [5. , 3. ],
       [4.9, 3.1],
       [6.7, 3.1],
       [5.1, 3.8],
       [6. , 3. ]])

In [4]:
# c_x = [6.5,6.6,6.7]
# c_y = [3.2,3.5,3.1]
# Centroid = np.array(list(zip(c_x,c_y)))
# Centroid

array([[6.5, 3.2],
       [6.6, 3.5],
       [6.7, 3.1]])

In [5]:
# Centroid_old = np.zeros(Centroid.shape)

In [6]:
# Centroid_old

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [7]:
# clusters = np.zeros(len(X))

In [8]:
# clusters

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
# def euclidean(a,b,ax=1):
#     return np.linalg.norm(a-b,axis=ax)

In [12]:
# error = euclidean(Centroid,Centroid_old,None)
# print(error)

12.759310326189265


In [14]:
# k=3
# iterr = 0
# while error != 0:
#     iterr = iterr + 1
#     for i in range(len(X)):
#         distances = euclidean(X[i], Centroid)
#         print("Distance: ", distances)
#         cluster = np.argmin(distances)
#         print("clusters: ", cluster)
#         clusters[i] = cluster
    
#     Centroid_old = deepcopy(Centroid)
    
#     for p in range(k):
#         points = [X[j] for j in range(len(X)) if clusters[j] == p ]
#         print("point: ", points)
#         Centroid[p] = np.mean(points, axis=0)
#     print("Centroid after iteration: ", iterr,"is: \n", Centroid)
#     error = euclidean(Centroid,Centroid_old,None)
#     print("Error: ", error)
            

Distance:  [0.6        0.76157731 0.80622577]
clusters:  0
Distance:  [1.92353841 2.0880613  2.10950231]
clusters:  0
Distance:  [0.5        0.80622577 0.58309519]
clusters:  0
Distance:  [1.8        1.92353841 2.00249844]
clusters:  0
Distance:  [1.41421356 1.30384048 1.62788206]
clusters:  1
Distance:  [1.5132746  1.67630546 1.70293864]
clusters:  0
Distance:  [1.60312195 1.74642492 1.8       ]
clusters:  0
Distance:  [0.2236068  0.41231056 0.        ]
clusters:  2
Distance:  [1.52315462 1.52970585 1.74642492]
clusters:  0
Distance:  [0.53851648 0.78102497 0.70710678]
clusters:  0
point:  [array([5.9, 3.2]), array([4.6, 2.9]), array([6.2, 2.8]), array([4.7, 3.2]), array([5., 3.]), array([4.9, 3.1]), array([5.1, 3.8]), array([6., 3.])]
point:  [array([5.5, 4.2])]
point:  [array([6.7, 3.1])]
Centroid after iteration:  1 is: 
 [[5.3   3.125]
 [5.5   4.2  ]
 [6.7   3.1  ]]
Error:  1.7735909900537947
Distance:  [0.60466933 1.07703296 0.80622577]
clusters:  0
Distance:  [0.73527206 1.58113

In [3]:
import pandas as pd
import numpy as np
from copy import deepcopy

In [5]:
data = pd.read_csv("kmeans.csv")
data

X1   X2
0  5.9  3.2
1  4.6  2.9
2  6.2  2.8
3  4.7  3.2
4  5.5  4.2
5  5.0  3.0
6  4.9  3.1
7  6.7  3.1
8  5.1  3.8
9  6.0  3.0

In [6]:
x1 = data["X1"]
x2 = data["X2"]

In [7]:
X = np.array(list(zip(x1,x2)))
X

array([[5.9, 3.2],
       [4.6, 2.9],
       [6.2, 2.8],
       [4.7, 3.2],
       [5.5, 4.2],
       [5. , 3. ],
       [4.9, 3.1],
       [6.7, 3.1],
       [5.1, 3.8],
       [6. , 3. ]])

In [26]:
cx = [6.2,6.6,6.5]
cy = [3.2,3.7,3.0]
Centroid = np.array(list(zip(cx,cy)))
Centroid

array([[6.2, 3.2],
       [6.6, 3.7],
       [6.5, 3. ]])

In [27]:
Centroid_old = np.zeros(Centroid.shape)
Centroid_old

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [28]:
clusters = np.zeros(len(X))
clusters

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [29]:
def euclidean(a,b,ax=1):
    return np.linalg.norm(a-b,axis=ax)

In [30]:
error = euclidean(Centroid,Centroid_old,None)
error

12.53714481052205

In [31]:
k=3
itter = 0
while error!=0:
    itter+=1
    for i in range(len(X)):
        distance = euclidean(X[i],Centroid)
        print("Distance= ",distance)
        cluster = np.argmin(distance)
        print("Cluster= ",cluster)
        clusters[i] = cluster
    
    Centroid_old = deepcopy(Centroid)
    
    for p in range(k):
        points = [X[j] for j in range(len(X)) if clusters[j] == p ]
        print("Points= ",points)
        Centroid[p] = np.mean(points,axis=0)
    print("Centroid after itteration ", itter, " is: \n",Centroid)
    error = euclidean(Centroid,Centroid_old,None)
    print("Error: ",error)
    

Distance=  [0.3        0.86023253 0.63245553]
Cluster=  0
Distance=  [1.62788206 2.15406592 1.90262976]
Cluster=  0
Distance=  [0.4        0.98488578 0.36055513]
Cluster=  2
Distance=  [1.5        1.96468827 1.81107703]
Cluster=  0
Distance=  [1.22065556 1.2083046  1.56204994]
Cluster=  1
Distance=  [1.21655251 1.74642492 1.5       ]
Cluster=  0
Distance=  [1.30384048 1.80277564 1.60312195]
Cluster=  0
Distance=  [0.50990195 0.60827625 0.2236068 ]
Cluster=  2
Distance=  [1.25299641 1.50332964 1.61245155]
Cluster=  0
Distance=  [0.28284271 0.92195445 0.5       ]
Cluster=  0
Points=  [array([5.9, 3.2]), array([4.6, 2.9]), array([4.7, 3.2]), array([5., 3.]), array([4.9, 3.1]), array([5.1, 3.8]), array([6., 3.])]
Points=  [array([5.5, 4.2])]
Points=  [array([6.2, 2.8]), array([6.7, 3.1])]
Centroid after itteration  1  is: 
 [[5.17142857 3.17142857]
 [5.5        4.2       ]
 [6.45       2.95      ]]
Error:  1.588639515498743
Distance=  [0.72913144 1.07703296 0.6041523 ]
Cluster=  2
Distance