In [46]:
import pandas as pd
import numpy as np
data = pd.read_csv("../glass.csv")
data.head()

Id       RI     Na    Mg    Al    Si      K    Ca   Ba   Fe  Type
0   1  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.0     1
1   2  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.0     1
2   3  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.0     1
3   4  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.0     1
4   5  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.0     1

In [47]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [48]:
print(scaler.fit_transform(data))

[[-1.72397593  0.87286765  0.28495326 ... -0.35287683 -0.5864509
  -0.84827468]
 [-1.70778837 -0.24933347  0.59181718 ... -0.35287683 -0.5864509
  -0.84827468]
 [-1.6916008  -0.72131806  0.14993314 ... -0.35287683 -0.5864509
  -0.84827468]
 ...
 [ 1.6916008   0.75404635  1.16872135 ...  2.95320036 -0.5864509
   2.01047778]
 [ 1.70778837 -0.61239854  1.19327046 ...  2.81208731 -0.5864509
   2.01047778]
 [ 1.72397593 -0.41436305  1.00915211 ...  3.01367739 -0.5864509
   2.01047778]]


In [49]:
x = data.drop("Type",axis=1)
x.head()

Id       RI     Na    Mg    Al    Si      K    Ca   Ba   Fe
0   1  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.0
1   2  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.0
2   3  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.0
3   4  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.0
4   5  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.0

In [50]:
y = data["Type"]
y.head()

0    1
1    1
2    1
3    1
4    1
Name: Type, dtype: int64

In [51]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y)

In [52]:
from sklearn.svm import SVC
model = SVC(kernel='linear')

In [53]:
model = model.fit(x_train,y_train)

In [54]:
y_pred = model.predict(x_test)

In [55]:
print(model.support_vectors_)
print(model.n_support_)

[[7.00000e+01 1.52300e+00 1.33100e+01 3.58000e+00 8.20000e-01 7.19900e+01
  1.20000e-01 1.01700e+01 0.00000e+00 3.00000e-02]
 [7.20000e+01 1.51848e+00 1.36400e+01 3.87000e+00 1.27000e+00 7.19600e+01
  5.40000e-01 8.32000e+00 0.00000e+00 3.20000e-01]
 [1.46000e+02 1.51839e+00 1.28500e+01 3.67000e+00 1.24000e+00 7.25700e+01
  6.20000e-01 8.68000e+00 0.00000e+00 3.50000e-01]
 [1.47000e+02 1.51769e+00 1.36500e+01 3.66000e+00 1.11000e+00 7.27700e+01
  1.10000e-01 8.60000e+00 0.00000e+00 0.00000e+00]
 [1.63000e+02 1.52211e+00 1.41900e+01 3.78000e+00 9.10000e-01 7.13600e+01
  2.30000e-01 9.14000e+00 0.00000e+00 3.70000e-01]
 [1.65000e+02 1.51915e+00 1.27300e+01 1.85000e+00 1.86000e+00 7.26900e+01
  6.00000e-01 1.00900e+01 0.00000e+00 0.00000e+00]
 [1.75000e+02 1.52058e+00 1.28500e+01 1.61000e+00 2.17000e+00 7.21800e+01
  7.60000e-01 9.70000e+00 2.40000e-01 5.10000e-01]
 [1.64000e+02 1.51514e+00 1.40100e+01 2.68000e+00 3.50000e+00 6.98900e+01
  1.68000e+00 5.87000e+00 2.20000e+00 0.00000e+00]


In [56]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print("Accuracy Score",accuracy_score(y_test,y_pred))

Accuracy Score 1.0


In [57]:
print("Confusion matrix: \n",confusion_matrix(y_test,y_pred))

Confusion matrix: 
 [[23  0  0  0  0  0]
 [ 0 18  0  0  0  0]
 [ 0  0  7  0  0  0]
 [ 0  0  0  3  0  0]
 [ 0  0  0  0  1  0]
 [ 0  0  0  0  0  2]]


In [58]:
print("Classification Report\n",classification_report(y_test,y_pred))

Classification Report
               precision    recall  f1-score   support

           1       1.00      1.00      1.00        23
           2       1.00      1.00      1.00        18
           3       1.00      1.00      1.00         7
           5       1.00      1.00      1.00         3
           6       1.00      1.00      1.00         1
           7       1.00      1.00      1.00         2

    accuracy                           1.00        54
   macro avg       1.00      1.00      1.00        54
weighted avg       1.00      1.00      1.00        54



In [59]:
model1 = SVC(kernel='rbf')

In [60]:
model2 = SVC(kernel='poly')

In [61]:
model3 = SVC(kernel='sigmoid')

In [62]:
model1 = model1.fit(x_train,y_train)
model2 = model2.fit(x_train,y_train)
model3 = model3.fit(x_train,y_train)

In [63]:
y_pred1 = model1.predict(x_test)
y_pred2 = model2.predict(x_test)
y_pred3 = model3.predict(x_test)

In [64]:
print("Accuracy Score rbf",accuracy_score(y_test,y_pred1))
print("Accuracy Score poly",accuracy_score(y_test,y_pred2))
print("Accuracy Score sigmoid",accuracy_score(y_test,y_pred3))

Accuracy Score rbf 0.7962962962962963
Accuracy Score poly 0.9629629629629629
Accuracy Score sigmoid 0.6481481481481481
